### ISSUE TITLE
Suggestion for "How do I engage with Microsoft" section on FAQ

### ISSUE THREAD

**Issue by atsatrom** [MicrosoftDocs/Compliance#13]
Answer states that a Microsoft HITRUST Administrator "will then complete their part of the assessment using their account on the MyCSF® tool." It would be great if the contact info be made available here or at least linked here in the event this administrator doesn't complete their part or it is taking an inappropriately long time to complete. 

I currently have a customer who is in this situation and we are seeking a way to connect with this person or team responsible for completed the assessment. 

Thanks for considering!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13cd61c1-630e-ea09-f95a-b191fc45ca97
* Version Independent ID: d7faae7a-74a8-367c-cfda-88fcc7315123
* Content: [Health Information Trust Alliance (HITRUST) Common Security Framework (CSF) - Microsoft Compliance](https://docs.microsoft.com/en-us/compliance/regulatory/offering-HITRUST#frequently-asked-questions)
* Content Source: [compliance/regulatory/offering-HITRUST.md](https://github.com/MicrosoftDocs/Compliance/blob/public/compliance/regulatory/offering-HITRUST.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@atsatrom - I’d recommend customers continue work through their Microsoft contact (this is the current process since they already have specific knowledge about their customer’s environments). If you're an internal MS contact, you can escalate any requests through internal processes. You can contact me internally for more information if needed, thanks.
